name: ESLint 🔎

on:
  push:
    branches:
      - main

env: # environment variables (available in any part of the action)
  NODE_VERSION: 18

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Install NodeJS
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
        env:
          NEXT_PUBLIC_SANITY_PROJECT_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_DATASET }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Code Linting
        run: npm run lint

