name: ESLint 🔎

on:
  push:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Install NodeJS
        env:
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Code Linting
        run: npm run lint
