name: Cypress Tests 🧪

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
      NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
      NEXT_PUBLIC_SANITY_API_VERSION: ${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION }}
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v2
      - name: Cypress build & run 🏗️
        uses: cypress-io/github-action@v4.2.0
        # build: npm run build
        with:
          working-directory: apps/frontend
          start: npm start
