name: Cypress E2E Tests 🧪

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Cypress E2E Tests 🧪
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    env:
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
      NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
      NEXT_PUBLIC_SANITY_API_VERSION: ${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION }}

    steps:
      - name: Check out code 🛒
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Cypress build & run 🏗️ 🏃‍♂️
        uses: cypress-io/github-action@v4.2.0
        with:
          working-directory: ./apps/frontend
          build: npm run build
          start: npm start
